name: "Win11 RDP + Tailscale (NAT OK)"
on:
  workflow_dispatch:

jobs:
  rdp-win11:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Docker & tools
        run: |
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get update
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli curl unzip

      - name: Jalankan Windows 11 container (NAT 3389)
        run: |
          sudo docker pull dockurr/windows:latest
          sudo docker rm -f win11 || true
          sudo docker run -d --name win11 \
            --privileged \
            -e VERSION=11 -e RAM_SIZE=6G -e CPU_CORES=4 \
            -p 3389:3389 dockurr/windows
          sleep 120

      - name: Install dan aktifkan Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo bash
          sudo tailscaled --tun userspace-networking --state=mem: --socket=/var/run/tailscale/tailscaled.sock &
          sleep 5

      - name: Login Tailscale dengan AuthKey
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=${TS_AUTHKEY} --hostname=rdp-win11-${{ github.run_id }} --ssh
          sudo tailscale status

      - name: Verifikasi port RDP Win11 via IP Tailscale
        run: |
          tailscale_ip=$(sudo tailscale ip -4 | head -n 1)
          echo "Win11 RDP aktif di Tailscale IP: $tailscale_ip"
          for i in {1..30}; do
            nc -z $tailscale_ip 3389 && echo "PORT 3389 OK di $tailscale_ip:3389" && break
            echo "Menunggu port 3389 RDP siap... [$i/30]"
            sleep 3
          done

      - name: Sesi tetap hidup
        run: sleep 3600
