name: "Windows 11 RDP + Tailscale (FINAL 2025)"

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- FIX Docker installation conflict ---
      - name: Fix containerd conflict and setup Docker
        run: |
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get update
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli socat qemu-system-x86 curl unzip

      # --- Jalankan Windows 11 VM menggunakan Dockurr ---
      - name: Start Windows 11 container
        run: |
          sudo docker pull dockurr/windows:latest
          sudo docker rm -f win11 || true
          sudo docker run -d --name win11 \
            --privileged \
            -e VERSION=11 \
            -e RAM_SIZE=6G \
            -e CPU_CORES=4 \
            -p 127.0.0.1:3389:3389 \
            dockurr/windows
          echo "Menunggu Windows VM booting (sekitar 2 menit)..."
          sleep 120

      # --- Install dan jalankan Tailscale daemon ---
      - name: Install and run Tailscale daemon
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo bash
          sudo tailscaled --tun userspace-networking --state=mem: --socket=/var/run/tailscale/tailscaled.sock &
          sleep 5

      # --- Autentikasi Tailscale dengan AuthKey ---
      - name: Authenticate with Tailscale
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=${TS_AUTHKEY} --hostname=github-rdp-${{ github.run_id }} --ssh
          sudo tailscale status

      # --- Perbaiki konflik socat dan forwarding ulang port 3389 ---
      - name: Start socat port forwarding
        run: |
          sudo pkill socat || true
          nohup socat TCP-LISTEN:3389,reuseaddr,fork TCP:127.0.0.1:3389 &
          sleep 5

      # --- Cek kesiapan koneksi RDP di jaringan Tailscale ---
      - name: Verify RDP connectivity
        run: |
          tailscale_ip=$(sudo tailscale ip -4 | head -n 1)
          echo "================================="
          echo "Tailscale node aktif di IP: $tailscale_ip"
          echo "Gunakan IP ini di Remote Desktop (mstsc)."
          echo "================================="
          timeout 90 bash -c \
            "until nc -z \$tailscale_ip 3389; do sleep 3; echo 'Menunggu port 3389 RDP siap...'; done"
          echo "Port 3389 terbuka! Sistem RDP sudah siap."

      # --- Pertahankan agar sesi tetap aktif ---
      - name: Keep alive session for remote desktop
        run: |
          echo "Menjaga koneksi tetap aktif selama 1 jam..."
          sleep 3600
