name: Windows RDP + Tailscale (2025 Fix)
on: workflow_dispatch

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Perbaiki containerd lalu install Docker
        run: |
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get update
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli socat qemu-system-x86 curl unzip

      - name: Jalankan Windows VM
        run: |
          sudo docker pull dockurr/windows:latest
          sudo docker rm -f win11 || true
          sudo docker run -d --name win11 --privileged -e VERSION=11 -e RAM_SIZE=6G -e CPU_CORES=4 -p 127.0.0.1:3389:3389 dockurr/windows
          sleep 120

      - name: Install dan aktifkan Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo bash
          sudo tailscaled --tun userspace-networking --state=mem: --socket=/var/run/tailscale/tailscaled.sock &
          sleep 5

      - name: Login Tailscale pakai authkey
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=${TS_AUTHKEY} --hostname=github-rdp-${{ github.run_id }} --ssh
          sudo tailscale status

      - name: Forward port 3389 ke Tailscale
        run: |
          nohup socat TCP-LISTEN:3389,reuseaddr,fork TCP:127.0.0.1:3389 &

      - name: Pastikan port RDP sudah terbuka di Tailscale
        run: |
          tailscale_ip=$(sudo tailscale ip -4 | head -n 1)
          echo "RDP siap di Tailscale IP: $tailscale_ip"
          timeout 60 bash -c 'until nc -z $tailscale_ip 3389; do sleep 3; echo "Waiting for port 3389..."; done'
          echo "Koneksi RDP ke $tailscale_ip:3389 SUKSES"

      - name: Biar akses RDP tetap hidup
        run: sleep 3600
